name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: "latest"
        actions-cache-folder: 'emsdk-cache'
    - name: Verify Emscripten
      run: emcc -v

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Setup Libraries
      run: sudo apt-get install -y pv
      run: ./install_libraries.sh

    - run: npm ci
    - run: npm run build
    # - run: npm run lint
    - run: npm test