name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: "latest"
        actions-cache-folder: 'emsdk-cache'

    - name: Verify Emscripten
      run: emcc -v

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache C++ Libs downloads
      uses: actions/cache@v2
      with:
        path: libraries/downloads
        key: c-libs-${{ hashFiles('package-lock.json') }}

    - name: Cache npm modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

    - run: ./install_libraries.sh
    - run: npm ci
    - run: npm run build
    # - run: npm run lint
    - run: npm test


    - name: Update build files
      uses: EndBug/add-and-commit@v7
      with:
        message: '[auto] update build files'
        add: build/Arrangement2D.* --force

    - name: Build examples
      run: npm run build-examples

    - name: Update examples files
      uses: EndBug/add-and-commit@v7
      with:
        message: '[auto] update examples files'
        add: build-examples --force
        push: 'origin HEAD:examples --force'





